'use strict';

// All images are verified football/soccer pitches, stadiums, or artificial turf fields
const IMGS = [
  'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&q=80',  // aerial green football pitch
  'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',  // football pitch aerial view
  'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',  // football stadium floodlights
  'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80',  // professional football stadium
  'https://images.unsplash.com/photo-1624880357913-a8539238245b?w=800&q=80',  // artificial turf five-a-side
  'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80',  // football pitch white lines
  'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80',  // football match in progress
  'https://images.unsplash.com/photo-1600679472829-3044539ce405?w=800&q=80',  // football pitch overhead
  'https://images.unsplash.com/photo-1625993051168-f9bf22945546?w=800&q=80',  // small-sided football field with goals
  'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80',  // football training session
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',  // football on artificial turf
  'https://images.unsplash.com/photo-1609710228159-0fa9bd7c0827?w=800&q=80',  // floodlit night football pitch
];

const img  = (i) => [IMGS[i % IMGS.length], IMGS[(i + 3) % IMGS.length]];
const ph   = (suffix) => `+96279${suffix}`;
const wa   = (suffix) => `+96277${suffix}`;

const ALL_AMENITIES = ['Parking', 'Cafeteria', 'Locker Rooms', 'Showers', 'Lighting', 'WiFi', 'Spectator Area'];
const amen = (...indices) => indices.map(i => ALL_AMENITIES[i]);

const fields = [

  // ══════════════════════════════════════════════════════════════
  //  AMMAN  (25 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: '6 Yard Sports & Entertainment', slug: '6-yard-sports-amman',
    city: 'عمان', region: 'وسط', location: 'عمان، شارع المدينة المنورة', address: 'شارع المدينة المنورة، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 35, rating: 4.7, reviewsCount: 142, featured: true,
    phone: ph('6660022'), whatsapp: wa('6660022'),
    amenities: amen(0,1,2,3,4,5,6), images: img(0),
    description: 'ملاعب كرة قدم داخلية وخارجية معتمدة من FIFA في قلب عمان.',
    coordinates: { lat: 31.9723, lng: 35.8942 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Soccer City Khalda', slug: 'soccer-city-khalda',
    city: 'عمان', region: 'غرب', location: 'عمان، خلدا', address: 'شارع خلدا الرئيسي، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 25, rating: 4.6, reviewsCount: 98, featured: true,
    phone: ph('2345678'), whatsapp: wa('2345678'),
    amenities: amen(0,4,5,6), images: img(1),
    description: 'موقع استراتيجي في خلدا مع ملاعب متعددة وإضاءة ليلية.',
    coordinates: { lat: 31.9791, lng: 35.8701 }, availableHours: { start: '09:00', end: '24:00' },
  },
  {
    name: 'The One Fields', slug: 'the-one-fields-mecca',
    city: 'عمان', region: 'وسط', location: 'عمان، شارع مكة', address: 'شارع مكة، عمان',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 40, rating: 4.8, reviewsCount: 186, featured: true,
    phone: ph('9871234'), whatsapp: wa('9871234'),
    amenities: amen(0,1,2,3,4,5,6), images: img(2),
    description: 'ملعب سباعي فاخر بعشب من الجيل السادس على شارع مكة.',
    coordinates: { lat: 31.9558, lng: 35.8833 }, availableHours: { start: '08:00', end: '01:00' },
  },
  {
    name: 'Knights Academy Fields', slug: 'knights-academy-airport',
    city: 'عمان', region: 'جنوب', location: 'عمان، طريق المطار', address: 'طريق المطار، عمان',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 30, rating: 4.6, reviewsCount: 77, featured: false,
    phone: ph('3456789'), whatsapp: wa('3456789'),
    amenities: amen(0,1,2,4,5), images: img(3),
    description: 'بيئة تدريبية احترافية مناسبة للأكاديميات والفرق.',
    coordinates: { lat: 31.9102, lng: 35.9432 }, availableHours: { start: '07:00', end: '23:00' },
  },
  {
    name: '442 Football Park - City Mall', slug: '442-city-mall',
    city: 'عمان', region: 'غرب', location: 'عمان، سيتي مول', address: 'سيتي مول، طريق المطار، عمان',
    type: '4v4', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 3.7, reviewsCount: 54, featured: false,
    phone: ph('1442442'), whatsapp: wa('1442442'),
    amenities: amen(0,1,4,5), images: img(4),
    description: 'أقفاص تدريب داخلية وملاعب صغيرة داخل سيتي مول.',
    coordinates: { lat: 31.9621, lng: 35.8619 }, availableHours: { start: '10:00', end: '22:00' },
  },
  {
    name: '442 Football Park - Abdali', slug: '442-abdali',
    city: 'عمان', region: 'وسط', location: 'عمان، عبدالي مول', address: 'عبدالي مول، عمان',
    type: '4v4', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.5, reviewsCount: 121, featured: false,
    phone: ph('1442443'), whatsapp: wa('1442443'),
    amenities: amen(0,1,4,5,6), images: img(5),
    description: 'تجربة كرة قدم بتقنية متطورة داخل عبدالي مول.',
    coordinates: { lat: 31.9726, lng: 35.9089 }, availableHours: { start: '10:00', end: '22:00' },
  },
  {
    name: 'Al Nashama Soccer Fields', slug: 'al-nashama-amman',
    city: 'عمان', region: 'شمال', location: 'عمان، شارع الجامعة', address: 'شارع الجامعة، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 25, rating: 4.5, reviewsCount: 93, featured: false,
    phone: ph('6438014'), whatsapp: wa('6438014'),
    amenities: amen(0,2,3,4,6), images: img(6),
    description: 'ملاعب خماسية وسداسية بمعايير FIFA في شارع الجامعة.',
    coordinates: { lat: 32.0021, lng: 35.8711 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Jordan Galaxy Stadium', slug: 'jordan-galaxy-amman',
    city: 'عمان', region: 'شرق', location: 'عمان، ماركا', address: 'ماركا، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.3, reviewsCount: 61, featured: false,
    phone: ph('2482828'), whatsapp: wa('2482828'),
    amenities: amen(0,4,5), images: img(7),
    description: 'ملاعب مضاءة بالكامل للعب الليلي في ماركا.',
    coordinates: { lat: 31.9921, lng: 35.9508 }, availableHours: { start: '08:00', end: '01:00' },
  },
  {
    name: 'Goal Masters Seventh Circle', slug: 'goal-masters-7th',
    city: 'عمان', region: 'غرب', location: 'عمان، الدوار السابع', address: 'الدوار السابع، عمان',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 32, rating: 4.4, reviewsCount: 88, featured: false,
    phone: ph('5551234'), whatsapp: wa('5551234'),
    amenities: amen(0,1,2,4,5,6), images: img(8),
    description: 'ملعب سداسي راقٍ بالقرب من الدوار السابع.',
    coordinates: { lat: 31.9648, lng: 35.8729 }, availableHours: { start: '09:00', end: '24:00' },
  },
  {
    name: 'Champions Arena Shmeisani', slug: 'champions-arena-shmeisani',
    city: 'عمان', region: 'وسط', location: 'عمان، الشميساني', address: 'الشميساني، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 28, rating: 4.2, reviewsCount: 72, featured: false,
    phone: ph('4445556'), whatsapp: wa('4445556'),
    amenities: amen(0,1,4,5), images: img(9),
    description: 'ملاعب الشميساني في قلب عمان التجاري.',
    coordinates: { lat: 31.9845, lng: 35.9021 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Green Pitch Gardens', slug: 'green-pitch-gardens',
    city: 'عمان', region: 'غرب', location: 'عمان، الجاردنز', address: 'الجاردنز، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 27, rating: 4.1, reviewsCount: 59, featured: false,
    phone: ph('7778889'), whatsapp: wa('7778889'),
    amenities: amen(0,2,3,4), images: img(10),
    description: 'ملعب مريح في الجاردنز مع خدمات متكاملة.',
    coordinates: { lat: 31.9672, lng: 35.8681 }, availableHours: { start: '09:00', end: '23:00' },
  },
  {
    name: 'Elite Soccer Rabia', slug: 'elite-soccer-rabia',
    city: 'عمان', region: 'غرب', location: 'عمان، الرابية', address: 'الرابية، عمان',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 45, rating: 4.9, reviewsCount: 201, featured: true,
    phone: ph('1112223'), whatsapp: wa('1112223'),
    amenities: amen(0,1,2,3,4,5,6), images: img(11),
    description: 'أرقى ملاعب عمان في منطقة الرابية الراقية.',
    coordinates: { lat: 31.9814, lng: 35.8618 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Pro Fields Abdali', slug: 'pro-fields-abdali',
    city: 'عمان', region: 'وسط', location: 'عمان، العبدلي', address: 'منطقة العبدلي، عمان',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 30, rating: 4.3, reviewsCount: 84, featured: false,
    phone: ph('3334445'), whatsapp: wa('3334445'),
    amenities: amen(0,1,2,4,6), images: img(0),
    description: 'ملاعب احترافية قرب منطقة العبدلي الجديدة.',
    coordinates: { lat: 31.9745, lng: 35.9063 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Star Arena Marj', slug: 'star-arena-marj',
    city: 'عمان', region: 'شرق', location: 'عمان، المرج', address: 'المرج، عمان',
    type: '5v5', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 18, rating: 3.8, reviewsCount: 34, featured: false,
    phone: ph('8889990'), whatsapp: wa('8889990'),
    amenities: amen(0,4), images: img(1),
    description: 'ملعب بعشب طبيعي بأسعار مناسبة في المرج.',
    coordinates: { lat: 31.9982, lng: 35.9671 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Royal Fields Jubaiha', slug: 'royal-fields-jubaiha',
    city: 'عمان', region: 'شمال', location: 'عمان، الجبيهة', address: 'الجبيهة، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.0, reviewsCount: 47, featured: false,
    phone: ph('6667778'), whatsapp: wa('6667778'),
    amenities: amen(0,2,4,5), images: img(2),
    description: 'ملاعب الجبيهة بالقرب من الجامعة الأردنية.',
    coordinates: { lat: 32.0112, lng: 35.8796 }, availableHours: { start: '09:00', end: '23:00' },
  },
  {
    name: 'Victory Sports Rashid', slug: 'victory-sports-rashid',
    city: 'عمان', region: 'جنوب', location: 'عمان، ضاحية الرشيد', address: 'ضاحية الرشيد، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 3.9, reviewsCount: 41, featured: false,
    phone: ph('2223334'), whatsapp: wa('2223334'),
    amenities: amen(0,4,6), images: img(3),
    description: 'ملاعب بأسعار معقولة في ضاحية الرشيد.',
    coordinates: { lat: 31.9234, lng: 35.9158 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Crown Fields Marj Al-Hamam', slug: 'crown-fields-marj-hamam',
    city: 'عمان', region: 'جنوب غرب', location: 'عمان، مرج الحمام', address: 'مرج الحمام، عمان',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 26, rating: 4.2, reviewsCount: 66, featured: false,
    phone: ph('5556667'), whatsapp: wa('5556667'),
    amenities: amen(0,1,2,4), images: img(4),
    description: 'ملعب سداسي مريح في منطقة مرج الحمام الهادئة.',
    coordinates: { lat: 31.9311, lng: 35.8723 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Premier Pitch Army Road', slug: 'premier-pitch-army-road',
    city: 'عمان', region: 'شمال', location: 'عمان، طريق الجيش', address: 'طريق الجيش، عمان',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 38, rating: 4.5, reviewsCount: 113, featured: true,
    phone: ph('9990001'), whatsapp: wa('9990001'),
    amenities: amen(0,1,2,3,4,5,6), images: img(5),
    description: 'ملعب سباعي احترافي على طريق الجيش بمرافق متكاملة.',
    coordinates: { lat: 32.0213, lng: 35.9012 }, availableHours: { start: '07:00', end: '01:00' },
  },
  {
    name: 'Falcon Sports Swaifiyeh', slug: 'falcon-sports-swaifiyeh',
    city: 'عمان', region: 'غرب', location: 'عمان، الصويفية', address: 'الصويفية، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 30, rating: 4.4, reviewsCount: 91, featured: false,
    phone: ph('4445555'), whatsapp: wa('4445555'),
    amenities: amen(0,1,2,3,4), images: img(6),
    description: 'ملاعب الصويفية الراقية للأنشطة الرياضية العائلية.',
    coordinates: { lat: 31.9634, lng: 35.8641 }, availableHours: { start: '09:00', end: '23:00' },
  },
  {
    name: "Legend's Arena Abdoun", slug: 'legends-arena-abdoun',
    city: 'عمان', region: 'غرب', location: 'عمان، عبدون', address: 'عبدون، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 33, rating: 4.6, reviewsCount: 107, featured: false,
    phone: ph('8887776'), whatsapp: wa('8887776'),
    amenities: amen(0,1,2,4,5,6), images: img(7),
    description: 'ملاعب راقية في عبدون مع خدمات VIP.',
    coordinates: { lat: 31.9698, lng: 35.8724 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Phoenix Fields Khreibet', slug: 'phoenix-fields-khreibet',
    city: 'عمان', region: 'شرق', location: 'عمان، خريبة السوق', address: 'خريبة السوق، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 3.8, reviewsCount: 29, featured: false,
    phone: ph('6665554'), whatsapp: wa('6665554'),
    amenities: amen(0,4), images: img(8),
    description: 'ملاعب بأسعار تنافسية في شرق عمان.',
    coordinates: { lat: 32.0045, lng: 35.9789 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Thunder Arena Gardens', slug: 'thunder-arena-gardens',
    city: 'عمان', region: 'غرب', location: 'عمان، الجاردنز', address: 'الجاردنز، عمان',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 28, rating: 4.1, reviewsCount: 55, featured: false,
    phone: ph('3332221'), whatsapp: wa('3332221'),
    amenities: amen(0,1,4,5), images: img(9),
    description: 'ملعب سداسي حديث في منطقة الجاردنز.',
    coordinates: { lat: 31.9655, lng: 35.8668 }, availableHours: { start: '09:00', end: '24:00' },
  },
  {
    name: 'Eagles Sports University St', slug: 'eagles-sports-university',
    city: 'عمان', region: 'شمال', location: 'عمان، شارع الجامعة', address: 'شارع الجامعة، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 3.9, reviewsCount: 38, featured: false,
    phone: ph('7776665'), whatsapp: wa('7776665'),
    amenities: amen(0,4,5,6), images: img(10),
    description: 'ملاعب شارع الجامعة المناسبة لطلاب الجامعات.',
    coordinates: { lat: 32.0034, lng: 35.8759 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Trax Sports Complex', slug: 'trax-sports-airport',
    city: 'عمان', region: 'جنوب', location: 'عمان، طريق المطار', address: 'طريق المطار، عمان',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 35, rating: 4.9, reviewsCount: 224, featured: true,
    phone: ph('5554443'), whatsapp: wa('5554443'),
    amenities: amen(0,1,2,3,4,5,6), images: img(11),
    description: 'مجمع ترا كس الرياضي — أحد أفخم المجمعات في عمان.',
    coordinates: { lat: 31.9148, lng: 35.9501 }, availableHours: { start: '08:00', end: '01:00' },
  },
  {
    name: 'Dynasty Fields Marka', slug: 'dynasty-fields-marka',
    city: 'عمان', region: 'شرق', location: 'عمان، ماركا', address: 'ماركا الجنوبية، عمان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 19, rating: 3.7, reviewsCount: 26, featured: false,
    phone: ph('2221110'), whatsapp: wa('2221110'),
    amenities: amen(0,4), images: img(0),
    description: 'ملاعب اقتصادية في ماركا الجنوبية.',
    coordinates: { lat: 31.9879, lng: 35.9612 }, availableHours: { start: '08:00', end: '22:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  ZARQA  (12 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'KHBP Football Field', slug: 'khbp-zarqa',
    city: 'الزرقاء', region: 'وسط', location: 'الزرقاء، شارع الملك عبدالله الثاني', address: 'شارع الملك عبدالله الثاني، الزرقاء',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 3.9, reviewsCount: 43, featured: false,
    phone: ph('1620626'), whatsapp: wa('1620626'),
    amenities: amen(0,4,6), images: img(1),
    description: 'ملعب سباعي في قلب الزرقاء على شارع الملك عبدالله.',
    coordinates: { lat: 32.0734, lng: 36.0812 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Zarqa Champions Fields', slug: 'zarqa-champions',
    city: 'الزرقاء', region: 'شمال', location: 'الزرقاء، الرصيفة', address: 'الرصيفة، الزرقاء',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.0, reviewsCount: 51, featured: false,
    phone: ph('3344556'), whatsapp: wa('3344556'),
    amenities: amen(0,1,4,5), images: img(2),
    description: 'ملاعب الرصيفة الشعبية بأسعار في متناول الجميع.',
    coordinates: { lat: 32.0967, lng: 36.0578 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Al Hashimiya Sports', slug: 'hashimiya-zarqa',
    city: 'الزرقاء', region: 'شرق', location: 'الزرقاء، الهاشمية', address: 'الهاشمية، الزرقاء',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.6, reviewsCount: 22, featured: false,
    phone: ph('4455667'), whatsapp: wa('4455667'),
    amenities: amen(0,4), images: img(3),
    description: 'ملعب الهاشمية الشعبي الأقرب للمجتمع.',
    coordinates: { lat: 32.1021, lng: 36.1234 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Blue Diamond Sports Zarqa', slug: 'blue-diamond-zarqa',
    city: 'الزرقاء', region: 'غرب', location: 'الزرقاء الجديدة', address: 'الزرقاء الجديدة',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 24, rating: 4.2, reviewsCount: 67, featured: false,
    phone: ph('5566778'), whatsapp: wa('5566778'),
    amenities: amen(0,1,2,4,5), images: img(4),
    description: 'ملعب سداسي حديث في الزرقاء الجديدة.',
    coordinates: { lat: 32.0612, lng: 36.0723 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Phoenix Sports Zarqa', slug: 'phoenix-zarqa',
    city: 'الزرقاء', region: 'وسط', location: 'الزرقاء، وسط المدينة', address: 'وسط المدينة، الزرقاء',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.7, reviewsCount: 31, featured: false,
    phone: ph('6677889'), whatsapp: wa('6677889'),
    amenities: amen(0,4,5), images: img(5),
    description: 'ملاعب وسط الزرقاء بأسعار تنافسية.',
    coordinates: { lat: 32.0748, lng: 36.0891 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Gold Fields Busman', slug: 'gold-fields-busman',
    city: 'الزرقاء', region: 'جنوب', location: 'الزرقاء، بسمان', address: 'بسمان، الزرقاء',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.6, reviewsCount: 18, featured: false,
    phone: ph('7788990'), whatsapp: wa('7788990'),
    amenities: amen(0,4), images: img(6),
    description: 'ملعب اقتصادي في منطقة بسمان.',
    coordinates: { lat: 32.0534, lng: 36.0967 }, availableHours: { start: '09:00', end: '22:00' },
  },
  {
    name: 'Tiger Sports Yarmouk', slug: 'tiger-yarmouk-zarqa',
    city: 'الزرقاء', region: 'شمال', location: 'الزرقاء، حي اليرموك', address: 'حي اليرموك، الزرقاء',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 21, rating: 4.0, reviewsCount: 48, featured: false,
    phone: ph('8890011'), whatsapp: wa('8890011'),
    amenities: amen(0,1,4,5,6), images: img(7),
    description: 'ملعب سداسي في حي اليرموك مع مرافق جيدة.',
    coordinates: { lat: 32.0889, lng: 36.0634 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Zarqa United Sports', slug: 'zarqa-united',
    city: 'الزرقاء', region: 'وسط', location: 'الزرقاء، شارع الأمير الحسن', address: 'شارع الأمير الحسن، الزرقاء',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 25, rating: 4.3, reviewsCount: 74, featured: true,
    phone: ph('9900112'), whatsapp: wa('9900112'),
    amenities: amen(0,1,2,4,5,6), images: img(8),
    description: 'ملعب سباعي فسيح على شارع الأمير الحسن.',
    coordinates: { lat: 32.0698, lng: 36.0856 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Flash Fields Mahatta', slug: 'flash-fields-mahatta',
    city: 'الزرقاء', region: 'وسط', location: 'الزرقاء، المحطة', address: 'المحطة، الزرقاء',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 15, rating: 3.5, reviewsCount: 14, featured: false,
    phone: ph('0011223'), whatsapp: wa('0011223'),
    amenities: amen(0,4), images: img(9),
    description: 'ملاعب المحطة الاقتصادية في الزرقاء.',
    coordinates: { lat: 32.0812, lng: 36.0923 }, availableHours: { start: '09:00', end: '22:00' },
  },
  {
    name: 'Storm Arena Ain Al-Basha', slug: 'storm-arena-ain-basha',
    city: 'الزرقاء', region: 'غرب', location: 'عين الباشا', address: 'عين الباشا، الزرقاء',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 3.8, reviewsCount: 27, featured: false,
    phone: ph('1122334'), whatsapp: wa('1122334'),
    amenities: amen(0,1,4), images: img(10),
    description: 'ملاعب عين الباشا بين عمان والزرقاء.',
    coordinates: { lat: 32.0421, lng: 36.0412 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Al Rusaifah Sports Hub', slug: 'rusaifah-sports-hub',
    city: 'الزرقاء', region: 'شمال', location: 'الرصيفة، الزرقاء', address: 'وسط الرصيفة، الزرقاء',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.9, reviewsCount: 33, featured: false,
    phone: ph('2233445'), whatsapp: wa('2233445'),
    amenities: amen(0,2,4,6), images: img(11),
    description: 'مركز رياضي في الرصيفة مع غرف تغيير.',
    coordinates: { lat: 32.1012, lng: 36.0534 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Zarqa Highland Fields', slug: 'zarqa-highland',
    city: 'الزرقاء', region: 'شمال', location: 'الزرقاء، المنطقة الصناعية', address: 'المنطقة الصناعية، الزرقاء',
    type: '6v6', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 20, rating: 3.7, reviewsCount: 21, featured: false,
    phone: ph('3344557'), whatsapp: wa('3344557'),
    amenities: amen(0,4,6), images: img(0),
    description: 'ملعب بعشب طبيعي في المنطقة الصناعية بالزرقاء.',
    coordinates: { lat: 32.0567, lng: 36.1023 }, availableHours: { start: '08:00', end: '21:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  IRBID  (12 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Al Nashama Soccer Fields Irbid', slug: 'nashama-irbid',
    city: 'إربد', region: 'وسط', location: 'إربد، شارع الجامعة', address: 'شارع الجامعة، إربد',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.4, reviewsCount: 88, featured: true,
    phone: ph('5566779'), whatsapp: wa('5566779'),
    amenities: amen(0,1,2,4,5), images: img(1),
    description: 'ملاعب الشمال الأولى في شارع الجامعة بإربد.',
    coordinates: { lat: 32.5567, lng: 35.8512 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Goal Fields Irbid', slug: 'goal-fields-irbid',
    city: 'إربد', region: 'وسط', location: 'إربد، شارع الثلاثين', address: 'شارع الثلاثين، إربد',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.3, reviewsCount: 76, featured: false,
    phone: ph('6677890'), whatsapp: wa('6677890'),
    amenities: amen(0,1,4,6), images: img(2),
    description: 'أفضل ملاعب إربد بأسعار مناسبة على شارع الثلاثين.',
    coordinates: { lat: 32.5489, lng: 35.8478 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Yarmouk University Fields', slug: 'yarmouk-university-fields',
    city: 'إربد', region: 'شمال', location: 'إربد، جامعة اليرموك', address: 'محيط جامعة اليرموك، إربد',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 15, rating: 4.0, reviewsCount: 52, featured: false,
    phone: ph('7788001'), whatsapp: wa('7788001'),
    amenities: amen(0,4,5), images: img(3),
    description: 'ملاعب الطلاب بالقرب من جامعة اليرموك.',
    coordinates: { lat: 32.5723, lng: 35.8234 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Northern Stars Irbid', slug: 'northern-stars-irbid',
    city: 'إربد', region: 'شمال', location: 'إربد، حي الأمير الحسين', address: 'حي الأمير الحسين، إربد',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.1, reviewsCount: 61, featured: false,
    phone: ph('8899112'), whatsapp: wa('8899112'),
    amenities: amen(0,1,2,4,5,6), images: img(4),
    description: 'ملعب سداسي في حي الأمير الحسين الراقي.',
    coordinates: { lat: 32.5634, lng: 35.8601 }, availableHours: { start: '09:00', end: '24:00' },
  },
  {
    name: 'Irbid Champions Arena', slug: 'irbid-champions',
    city: 'إربد', region: 'جنوب', location: 'إربد، المنطقة الحرة', address: 'المنطقة الحرة، إربد',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 28, rating: 4.5, reviewsCount: 103, featured: true,
    phone: ph('9900223'), whatsapp: wa('9900223'),
    amenities: amen(0,1,2,3,4,5,6), images: img(5),
    description: 'أكبر ملاعب إربد بالقرب من المنطقة الحرة.',
    coordinates: { lat: 32.5312, lng: 35.8789 }, availableHours: { start: '07:00', end: '01:00' },
  },
  {
    name: 'Green Fields Irbid', slug: 'green-fields-irbid',
    city: 'إربد', region: 'غرب', location: 'إربد، حي الإسكان', address: 'حي الإسكان، إربد',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.8, reviewsCount: 33, featured: false,
    phone: ph('0011334'), whatsapp: wa('0011334'),
    amenities: amen(0,4,5), images: img(6),
    description: 'ملاعب حي الإسكان بأسعار مناسبة.',
    coordinates: { lat: 32.5445, lng: 35.8345 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Pro Arena Irbid', slug: 'pro-arena-irbid',
    city: 'إربد', region: 'وسط', location: 'إربد، النزهة', address: 'النزهة، إربد',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 19, rating: 4.0, reviewsCount: 45, featured: false,
    phone: ph('1122445'), whatsapp: wa('1122445'),
    amenities: amen(0,1,4,6), images: img(7),
    description: 'ملاعب النزهة في إربد مع كافتيريا ومواقف.',
    coordinates: { lat: 32.5512, lng: 35.8523 }, availableHours: { start: '09:00', end: '23:00' },
  },
  {
    name: 'Knights Fields Irbid', slug: 'knights-irbid',
    city: 'إربد', region: 'شمال', location: 'إربد، بيت راس', address: 'بيت راس، إربد',
    type: '5v5', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 16, rating: 3.7, reviewsCount: 24, featured: false,
    phone: ph('2233556'), whatsapp: wa('2233556'),
    amenities: amen(0,4), images: img(8),
    description: 'ملعب بعشب طبيعي في بيت راس شمال إربد.',
    coordinates: { lat: 32.5889, lng: 35.8423 }, availableHours: { start: '08:00', end: '21:00' },
  },
  {
    name: 'Elite Arena Irbid', slug: 'elite-arena-irbid',
    city: 'إربد', region: 'وسط', location: 'إربد، الحصن', address: 'الحصن، إربد',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 23, rating: 4.2, reviewsCount: 69, featured: false,
    phone: ph('3344668'), whatsapp: wa('3344668'),
    amenities: amen(0,1,2,4,5), images: img(9),
    description: 'ملعب سداسي في منطقة الحصن.',
    coordinates: { lat: 32.5623, lng: 35.8712 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Irbid Sports Palace', slug: 'irbid-sports-palace',
    city: 'إربد', region: 'جنوب', location: 'إربد، حي الاتحاد', address: 'حي الاتحاد، إربد',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 26, rating: 4.4, reviewsCount: 85, featured: false,
    phone: ph('4455779'), whatsapp: wa('4455779'),
    amenities: amen(0,1,2,3,4,5), images: img(10),
    description: 'قصر الرياضة في إربد بملاعب من الدرجة الأولى.',
    coordinates: { lat: 32.5378, lng: 35.8645 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Summit Fields Irbid', slug: 'summit-irbid',
    city: 'إربد', region: 'غرب', location: 'إربد، البارحة', address: 'البارحة، إربد',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 3.9, reviewsCount: 36, featured: false,
    phone: ph('5566890'), whatsapp: wa('5566890'),
    amenities: amen(0,4,5,6), images: img(11),
    description: 'ملاعب غرب إربد القريبة من البارحة.',
    coordinates: { lat: 32.5401, lng: 35.8312 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Victory Arena Shajara', slug: 'victory-shajara',
    city: 'إربد', region: 'شمال', location: 'إربد، الشجرة', address: 'الشجرة، إربد',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.6, reviewsCount: 19, featured: false,
    phone: ph('6677001'), whatsapp: wa('6677001'),
    amenities: amen(0,4), images: img(0),
    description: 'ملاعب الشجرة شمال إربد بأسعار في متناول الجميع.',
    coordinates: { lat: 32.5934, lng: 35.8534 }, availableHours: { start: '09:00', end: '22:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  AQABA  (8 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Aqaba Stadium Mini Fields', slug: 'aqaba-stadium-mini',
    city: 'العقبة', region: 'وسط', location: 'العقبة، وسط المدينة', address: 'وسط المدينة، العقبة',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.2, reviewsCount: 55, featured: false,
    phone: ph('0335179'), whatsapp: wa('0335179'),
    amenities: amen(0,1,4,5,6), images: img(1),
    description: 'ملاعب ميني قرب استاد العقبة — مفتوحة طوال اليوم.',
    coordinates: { lat: 29.5267, lng: 35.0060 }, availableHours: { start: '07:00', end: '24:00' },
  },
  {
    name: 'Red Sea Sports Marina', slug: 'red-sea-marina-aqaba',
    city: 'العقبة', region: 'شمال', location: 'العقبة، المارينا', address: 'المارينا، العقبة',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 25, rating: 4.5, reviewsCount: 87, featured: true,
    phone: ph('1234567'), whatsapp: wa('1234567'),
    amenities: amen(0,1,2,3,4,5,6), images: img(2),
    description: 'ملاعب البحر الأحمر الفاخرة بإطلالة على الخليج.',
    coordinates: { lat: 29.5389, lng: 35.0089 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Port City Fields Aqaba', slug: 'port-city-aqaba',
    city: 'العقبة', region: 'جنوب', location: 'العقبة، ميناء العقبة', address: 'محيط ميناء العقبة',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.0, reviewsCount: 41, featured: false,
    phone: ph('2345670'), whatsapp: wa('2345670'),
    amenities: amen(0,4,5,6), images: img(3),
    description: 'ملعب سداسي بجانب ميناء العقبة التجاري.',
    coordinates: { lat: 29.5178, lng: 35.0034 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Gulf Sports Aqaba', slug: 'gulf-sports-aqaba',
    city: 'العقبة', region: 'وسط', location: 'العقبة، قرية الدبة', address: 'قرية الدبة، العقبة',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.1, reviewsCount: 48, featured: false,
    phone: ph('3456701'), whatsapp: wa('3456701'),
    amenities: amen(0,1,4,6), images: img(4),
    description: 'ملاعب قرية الدبة في ضواحي العقبة.',
    coordinates: { lat: 29.5112, lng: 34.9978 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Aqaba Champions South Beach', slug: 'aqaba-champions-south',
    city: 'العقبة', region: 'جنوب', location: 'العقبة، الشاطئ الجنوبي', address: 'الشاطئ الجنوبي، العقبة',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 23, rating: 4.3, reviewsCount: 63, featured: false,
    phone: ph('4567012'), whatsapp: wa('4567012'),
    amenities: amen(0,1,2,4,5), images: img(5),
    description: 'ملاعب الشاطئ الجنوبي بإطلالة بحرية.',
    coordinates: { lat: 29.5034, lng: 35.0012 }, availableHours: { start: '07:00', end: '24:00' },
  },
  {
    name: 'Pearl Fields Aqaba', slug: 'pearl-fields-aqaba',
    city: 'العقبة', region: 'شمال', location: 'العقبة، حي النخيل', address: 'حي النخيل، العقبة',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 30, rating: 4.6, reviewsCount: 94, featured: true,
    phone: ph('5678123'), whatsapp: wa('5678123'),
    amenities: amen(0,1,2,3,4,5,6), images: img(6),
    description: 'ملعب سباعي متكامل في حي النخيل.',
    coordinates: { lat: 29.5412, lng: 35.0134 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Coral Sports Aqaba', slug: 'coral-sports-aqaba',
    city: 'العقبة', region: 'وسط', location: 'العقبة، حي الكورنيش', address: 'الكورنيش، العقبة',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.0, reviewsCount: 39, featured: false,
    phone: ph('6789234'), whatsapp: wa('6789234'),
    amenities: amen(0,1,4,5,6), images: img(7),
    description: 'ملاعب الكورنيش الممتدة على ساحل البحر الأحمر.',
    coordinates: { lat: 29.5301, lng: 35.0078 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Aqaba Elite Academy', slug: 'aqaba-elite-academy',
    city: 'العقبة', region: 'وسط', location: 'العقبة، حي الزيتون', address: 'حي الزيتون، العقبة',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 24, rating: 4.2, reviewsCount: 57, featured: false,
    phone: ph('7890345'), whatsapp: wa('7890345'),
    amenities: amen(0,1,2,4,5), images: img(8),
    description: 'أكاديمية العقبة الرياضية مع مدربين محترفين.',
    coordinates: { lat: 29.5234, lng: 35.0045 }, availableHours: { start: '08:00', end: '23:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  SALT  (8 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Salt Stars Sports', slug: 'salt-stars',
    city: 'السلط', region: 'وسط', location: 'السلط، وسط المدينة', address: 'وسط المدينة، السلط',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.0, reviewsCount: 42, featured: false,
    phone: ph('8901456'), whatsapp: wa('8901456'),
    amenities: amen(0,1,4,5), images: img(9),
    description: 'ملاعب السلط الرئيسية في قلب المدينة.',
    coordinates: { lat: 32.0392, lng: 35.7278 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Green Hills Fields Salt', slug: 'green-hills-salt',
    city: 'السلط', region: 'شمال', location: 'السلط، منطقة العيون', address: 'العيون، السلط',
    type: '5v5', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 16, rating: 3.8, reviewsCount: 27, featured: false,
    phone: ph('9012567'), whatsapp: wa('9012567'),
    amenities: amen(0,4,6), images: img(10),
    description: 'ملعب بعشب طبيعي في التلال الخضراء شمال السلط.',
    coordinates: { lat: 32.0523, lng: 35.7189 }, availableHours: { start: '08:00', end: '21:00' },
  },
  {
    name: 'Ancient City Sports Salt', slug: 'ancient-city-salt',
    city: 'السلط', region: 'وسط', location: 'السلط القديمة', address: 'المدينة القديمة، السلط',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.1, reviewsCount: 48, featured: false,
    phone: ph('0123678'), whatsapp: wa('0123678'),
    amenities: amen(0,1,4,5,6), images: img(11),
    description: 'ملاعب السلط التاريخية بجانب المدينة القديمة.',
    coordinates: { lat: 32.0345, lng: 35.7312 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Salt Champions Arena', slug: 'salt-champions',
    city: 'السلط', region: 'جنوب', location: 'السلط، أم جوزة', address: 'أم جوزة، السلط',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.2, reviewsCount: 54, featured: false,
    phone: ph('1234789'), whatsapp: wa('1234789'),
    amenities: amen(0,1,2,4,5), images: img(0),
    description: 'ملعب سداسي في ضواحي السلط الجنوبية.',
    coordinates: { lat: 32.0234, lng: 35.7401 }, availableHours: { start: '09:00', end: '23:00' },
  },
  {
    name: 'Jordan Valley Fields Salt', slug: 'jordan-valley-salt',
    city: 'السلط', region: 'غرب', location: 'السلط، الشونة الجنوبية', address: 'الشونة الجنوبية، السلط',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 15, rating: 3.7, reviewsCount: 21, featured: false,
    phone: ph('2345890'), whatsapp: wa('2345890'),
    amenities: amen(0,4), images: img(1),
    description: 'ملاعب الغور بالقرب من نهر الأردن.',
    coordinates: { lat: 31.9801, lng: 35.6345 }, availableHours: { start: '07:00', end: '20:00' },
  },
  {
    name: 'Salt Elite Fields', slug: 'salt-elite',
    city: 'السلط', region: 'وسط', location: 'السلط، حي الزهور', address: 'حي الزهور، السلط',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 19, rating: 3.9, reviewsCount: 35, featured: false,
    phone: ph('3456901'), whatsapp: wa('3456901'),
    amenities: amen(0,1,4,5), images: img(2),
    description: 'ملاعب حي الزهور الهادئة في السلط.',
    coordinates: { lat: 32.0412, lng: 35.7234 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Highland Sports Salt', slug: 'highland-salt',
    city: 'السلط', region: 'شمال', location: 'السلط، تلة العبدلات', address: 'تلة العبدلات، السلط',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 25, rating: 4.3, reviewsCount: 61, featured: false,
    phone: ph('4568012'), whatsapp: wa('4568012'),
    amenities: amen(0,1,2,4,5,6), images: img(3),
    description: 'ملعب سباعي على التلال بمنظر بانورامي رائع.',
    coordinates: { lat: 32.0567, lng: 35.7123 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Kfarjaa Sports Salt', slug: 'kfarjaa-salt',
    city: 'السلط', region: 'شمال', location: 'السلط، كفرجا', address: 'كفرجا، السلط',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.8, reviewsCount: 26, featured: false,
    phone: ph('5679123'), whatsapp: wa('5679123'),
    amenities: amen(0,4), images: img(4),
    description: 'ملاعب كفرجا الريفية بأجواء هادئة.',
    coordinates: { lat: 32.0678, lng: 35.7067 }, availableHours: { start: '08:00', end: '22:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  MADABA  (8 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Madaba Stars Sports', slug: 'madaba-stars',
    city: 'مادبا', region: 'وسط', location: 'مادبا، وسط المدينة', address: 'وسط المدينة، مادبا',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.0, reviewsCount: 45, featured: false,
    phone: ph('6790234'), whatsapp: wa('6790234'),
    amenities: amen(0,1,4,5), images: img(5),
    description: 'ملاعب مادبا الرئيسية في قلب المدينة السياحية.',
    coordinates: { lat: 31.7179, lng: 35.7900 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Mosaic Sports Madaba', slug: 'mosaic-madaba',
    city: 'مادبا', region: 'وسط', location: 'مادبا، ميدان القديسين', address: 'ميدان القديسين، مادبا',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.1, reviewsCount: 52, featured: false,
    phone: ph('7801345'), whatsapp: wa('7801345'),
    amenities: amen(0,1,4,5,6), images: img(6),
    description: 'ملاعب الفسيفساء قرب مركز مدينة مادبا.',
    coordinates: { lat: 31.7213, lng: 35.7934 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Heritage Fields Madaba', slug: 'heritage-madaba',
    city: 'مادبا', region: 'جنوب', location: 'مادبا، الربضة', address: 'الربضة، مادبا',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.2, reviewsCount: 58, featured: false,
    phone: ph('8912456'), whatsapp: wa('8912456'),
    amenities: amen(0,1,2,4,5), images: img(7),
    description: 'ملعب سداسي في منطقة الربضة الأثرية.',
    coordinates: { lat: 31.7134, lng: 35.7867 }, availableHours: { start: '09:00', end: '23:00' },
  },
  {
    name: 'Madaba Arena', slug: 'madaba-arena',
    city: 'مادبا', region: 'شمال', location: 'مادبا، حي القاسم', address: 'حي القاسم، مادبا',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.8, reviewsCount: 31, featured: false,
    phone: ph('9023567'), whatsapp: wa('9023567'),
    amenities: amen(0,4,5), images: img(8),
    description: 'ملعب حي القاسم في شمال مادبا.',
    coordinates: { lat: 31.7256, lng: 35.7945 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Desert Rose Sports Madaba', slug: 'desert-rose-madaba',
    city: 'مادبا', region: 'غرب', location: 'مادبا، الحمرا', address: 'الحمرا، مادبا',
    type: '5v5', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 15, rating: 3.6, reviewsCount: 18, featured: false,
    phone: ph('0134678'), whatsapp: wa('0134678'),
    amenities: amen(0,4), images: img(9),
    description: 'ملعب بعشب طبيعي في الريف الغربي لمادبا.',
    coordinates: { lat: 31.7101, lng: 35.7723 }, availableHours: { start: '08:00', end: '21:00' },
  },
  {
    name: 'Jordan Mosaic Sports', slug: 'jordan-mosaic-sports',
    city: 'مادبا', region: 'وسط', location: 'مادبا، الجنوبي', address: 'الجنوبي، مادبا',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 27, rating: 4.4, reviewsCount: 71, featured: true,
    phone: ph('1245789'), whatsapp: wa('1245789'),
    amenities: amen(0,1,2,3,4,5,6), images: img(10),
    description: 'أكبر ملعب في مادبا بمرافق متكاملة.',
    coordinates: { lat: 31.7145, lng: 35.7912 }, availableHours: { start: '08:00', end: '24:00' },
  },
  {
    name: 'Madaba Champions', slug: 'madaba-champions',
    city: 'مادبا', region: 'شرق', location: 'مادبا، نجع', address: 'نجع، مادبا',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.7, reviewsCount: 22, featured: false,
    phone: ph('2356890'), whatsapp: wa('2356890'),
    amenities: amen(0,4,5), images: img(11),
    description: 'ملاعب نجع شرق مادبا.',
    coordinates: { lat: 31.7312, lng: 35.8012 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Golden Fields Madaba', slug: 'golden-madaba',
    city: 'مادبا', region: 'وسط', location: 'مادبا، الجامعة', address: 'قرب جامعة مادبا',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 19, rating: 4.0, reviewsCount: 43, featured: false,
    phone: ph('3467901'), whatsapp: wa('3467901'),
    amenities: amen(0,1,4,5), images: img(0),
    description: 'ملاعب جامعة مادبا للطلاب والمجتمع.',
    coordinates: { lat: 31.7234, lng: 35.7856 }, availableHours: { start: '08:00', end: '23:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  JERASH  (5 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Jerash Sports Arena', slug: 'jerash-sports-arena',
    city: 'جرش', region: 'وسط', location: 'جرش، وسط المدينة', address: 'وسط المدينة، جرش',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.0, reviewsCount: 37, featured: false,
    phone: ph('4578012'), whatsapp: wa('4578012'),
    amenities: amen(0,1,4,5,6), images: img(1),
    description: 'ملاعب جرش الأثرية بالقرب من المدرج الروماني.',
    coordinates: { lat: 32.2750, lng: 35.8914 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Roman Columns Sports', slug: 'roman-columns-jerash',
    city: 'جرش', region: 'وسط', location: 'جرش، شارع الأعمدة', address: 'شارع الأعمدة، جرش',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.3, reviewsCount: 59, featured: true,
    phone: ph('5689123'), whatsapp: wa('5689123'),
    amenities: amen(0,1,2,4,5), images: img(2),
    description: 'ملعب سداسي بجانب شارع الأعمدة الشهير.',
    coordinates: { lat: 32.2812, lng: 35.8956 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'North Fields Jerash', slug: 'north-jerash',
    city: 'جرش', region: 'شمال', location: 'جرش، الأحياء الشمالية', address: 'الأحياء الشمالية، جرش',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.8, reviewsCount: 24, featured: false,
    phone: ph('6790234'), whatsapp: wa('6790234'),
    amenities: amen(0,4,5), images: img(3),
    description: 'ملاعب الأحياء الشمالية بجرش.',
    coordinates: { lat: 32.2934, lng: 35.8878 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Champions Jerash', slug: 'champions-jerash',
    city: 'جرش', region: 'جنوب', location: 'جرش، الأحياء الجنوبية', address: 'الأحياء الجنوبية، جرش',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.9, reviewsCount: 29, featured: false,
    phone: ph('7801345'), whatsapp: wa('7801345'),
    amenities: amen(0,1,4), images: img(4),
    description: 'ملاعب جنوب جرش الشعبية.',
    coordinates: { lat: 32.2634, lng: 35.8834 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Souf Valley Sports', slug: 'souf-jerash',
    city: 'جرش', region: 'غرب', location: 'جرش، سوف', address: 'سوف، جرش',
    type: '5v5', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 15, rating: 3.6, reviewsCount: 16, featured: false,
    phone: ph('8912456'), whatsapp: wa('8912456'),
    amenities: amen(0,4), images: img(5),
    description: 'ملعب ريفي بعشب طبيعي في منطقة سوف.',
    coordinates: { lat: 32.2512, lng: 35.8712 }, availableHours: { start: '08:00', end: '20:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  AJLOUN  (5 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Ajloun Castle Sports', slug: 'ajloun-castle-sports',
    city: 'عجلون', region: 'وسط', location: 'عجلون، وسط المدينة', address: 'وسط المدينة، عجلون',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.1, reviewsCount: 41, featured: false,
    phone: ph('9023567'), whatsapp: wa('9023567'),
    amenities: amen(0,1,4,5,6), images: img(6),
    description: 'ملاعب عجلون بإطلالة على قلعة عجلون.',
    coordinates: { lat: 32.3341, lng: 35.7503 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Forest Fields Kufr Anja', slug: 'forest-kufr-anja',
    city: 'عجلون', region: 'شمال', location: 'عجلون، كفرنجة', address: 'كفرنجة، عجلون',
    type: '5v5', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 15, rating: 3.7, reviewsCount: 22, featured: false,
    phone: ph('0134678'), whatsapp: wa('0134678'),
    amenities: amen(0,4), images: img(7),
    description: 'ملعب بعشب طبيعي وسط أحراش كفرنجة.',
    coordinates: { lat: 32.3489, lng: 35.7312 }, availableHours: { start: '08:00', end: '20:00' },
  },
  {
    name: 'Green Mountain Ajloun', slug: 'green-mountain-ajloun',
    city: 'عجلون', region: 'وسط', location: 'عجلون، جبل عجلون', address: 'جبل عجلون',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.9, reviewsCount: 30, featured: false,
    phone: ph('1245789'), whatsapp: wa('1245789'),
    amenities: amen(0,4,5,6), images: img(8),
    description: 'ملاعب جبل عجلون الخضراء بأجواء نقية.',
    coordinates: { lat: 32.3412, lng: 35.7412 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Ajloun Valley Arena', slug: 'ajloun-valley',
    city: 'عجلون', region: 'جنوب', location: 'عجلون، وادي الريان', address: 'وادي الريان، عجلون',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.2, reviewsCount: 48, featured: false,
    phone: ph('2356890'), whatsapp: wa('2356890'),
    amenities: amen(0,1,2,4,5), images: img(9),
    description: 'ملعب وادي الريان السداسي في عجلون.',
    coordinates: { lat: 32.3234, lng: 35.7567 }, availableHours: { start: '09:00', end: '23:00' },
  },
  {
    name: 'Highland Fields Ajloun', slug: 'highland-ajloun',
    city: 'عجلون', region: 'شمال', location: 'عجلون، عنجرة', address: 'عنجرة، عجلون',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.8, reviewsCount: 25, featured: false,
    phone: ph('3467901'), whatsapp: wa('3467901'),
    amenities: amen(0,4), images: img(10),
    description: 'ملاعب عنجرة في الجزء الشمالي من عجلون.',
    coordinates: { lat: 32.3567, lng: 35.7234 }, availableHours: { start: '08:00', end: '22:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  MAFRAQ  (5 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Mafraq Sports Arena', slug: 'mafraq-sports',
    city: 'المفرق', region: 'وسط', location: 'المفرق، وسط المدينة', address: 'وسط المدينة، المفرق',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.8, reviewsCount: 28, featured: false,
    phone: ph('4578012'), whatsapp: wa('4578012'),
    amenities: amen(0,4,5), images: img(11),
    description: 'ملاعب المفرق الرئيسية في قلب المدينة.',
    coordinates: { lat: 32.3436, lng: 36.2083 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Desert Stars Mafraq', slug: 'desert-stars-mafraq',
    city: 'المفرق', region: 'شرق', location: 'المفرق، الرويشد', address: 'الرويشد، المفرق',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 15, rating: 3.6, reviewsCount: 16, featured: false,
    phone: ph('5689123'), whatsapp: wa('5689123'),
    amenities: amen(0,4), images: img(0),
    description: 'ملاعب الرويشد على الحدود الشرقية.',
    coordinates: { lat: 32.5123, lng: 38.1834 }, availableHours: { start: '08:00', end: '21:00' },
  },
  {
    name: 'Northern Arena Mafraq', slug: 'northern-mafraq',
    city: 'المفرق', region: 'شمال', location: 'المفرق، الشمال', address: 'الجزء الشمالي، المفرق',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.7, reviewsCount: 20, featured: false,
    phone: ph('6790234'), whatsapp: wa('6790234'),
    amenities: amen(0,1,4,5), images: img(1),
    description: 'ملاعب الشمال المفرقية.',
    coordinates: { lat: 32.3712, lng: 36.2123 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Al Badiya Sports Hub', slug: 'badiya-mafraq',
    city: 'المفرق', region: 'جنوب', location: 'المفرق، صماد', address: 'صماد، المفرق',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.0, reviewsCount: 35, featured: false,
    phone: ph('7801345'), whatsapp: wa('7801345'),
    amenities: amen(0,1,4,5,6), images: img(2),
    description: 'مركز البادية الرياضي في صماد.',
    coordinates: { lat: 32.3201, lng: 36.1834 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Mafraq Elite Fields', slug: 'mafraq-elite',
    city: 'المفرق', region: 'وسط', location: 'المفرق، الحي الشرقي', address: 'الحي الشرقي، المفرق',
    type: '7v7', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 22, rating: 4.1, reviewsCount: 43, featured: false,
    phone: ph('8912456'), whatsapp: wa('8912456'),
    amenities: amen(0,1,2,4,5,6), images: img(3),
    description: 'ملعب سباعي في المفرق مع مرافق متكاملة.',
    coordinates: { lat: 32.3489, lng: 36.2201 }, availableHours: { start: '08:00', end: '23:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  KARAK  (5 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Karak Castle Sports', slug: 'karak-castle-sports',
    city: 'الكرك', region: 'وسط', location: 'الكرك، وسط المدينة', address: 'وسط المدينة، الكرك',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 18, rating: 4.0, reviewsCount: 38, featured: false,
    phone: ph('9023567'), whatsapp: wa('9023567'),
    amenities: amen(0,1,4,5), images: img(4),
    description: 'ملاعب الكرك بإطلالة على القلعة التاريخية.',
    coordinates: { lat: 31.1806, lng: 35.7042 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Southern Stars Karak', slug: 'southern-stars-karak',
    city: 'الكرك', region: 'جنوب', location: 'الكرك، الغور', address: 'الغور، الكرك',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.8, reviewsCount: 27, featured: false,
    phone: ph('0134678'), whatsapp: wa('0134678'),
    amenities: amen(0,4,6), images: img(5),
    description: 'ملاعب غور الكرك على ضفاف البحر الميت.',
    coordinates: { lat: 31.1234, lng: 35.6234 }, availableHours: { start: '07:00', end: '21:00' },
  },
  {
    name: 'Karak Arena', slug: 'karak-arena',
    city: 'الكرك', region: 'وسط', location: 'الكرك، الجنوبي', address: 'الجنوبي، الكرك',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.1, reviewsCount: 47, featured: false,
    phone: ph('1245789'), whatsapp: wa('1245789'),
    amenities: amen(0,1,2,4,5), images: img(6),
    description: 'ملعب سداسي احترافي في الكرك.',
    coordinates: { lat: 31.1723, lng: 35.7123 }, availableHours: { start: '08:00', end: '23:00' },
  },
  {
    name: 'Jordan Valley South Sports', slug: 'jv-south-karak',
    city: 'الكرك', region: 'غرب', location: 'الكرك، المزار الجنوبي', address: 'المزار الجنوبي، الكرك',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.9, reviewsCount: 31, featured: false,
    phone: ph('2356890'), whatsapp: wa('2356890'),
    amenities: amen(0,4,5,6), images: img(7),
    description: 'ملاعب المزار الجنوبي في الكرك.',
    coordinates: { lat: 31.0934, lng: 35.7312 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Mazar Al-Sharif Fields', slug: 'mazar-sharif-karak',
    city: 'الكرك', region: 'شمال', location: 'الكرك، الشمالي', address: 'الشمالي، الكرك',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 16, rating: 3.7, reviewsCount: 22, featured: false,
    phone: ph('3467901'), whatsapp: wa('3467901'),
    amenities: amen(0,4), images: img(8),
    description: 'ملاعب شمال الكرك بأسعار مناسبة.',
    coordinates: { lat: 31.2101, lng: 35.7234 }, availableHours: { start: '08:00', end: '22:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  TAFILAH  (4 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Tafilah Sports Arena', slug: 'tafilah-arena',
    city: 'الطفيلة', region: 'وسط', location: 'الطفيلة، وسط المدينة', address: 'وسط المدينة، الطفيلة',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.8, reviewsCount: 24, featured: false,
    phone: ph('4578012'), whatsapp: wa('4578012'),
    amenities: amen(0,1,4,5), images: img(9),
    description: 'ملاعب الطفيلة الرئيسية في المدينة.',
    coordinates: { lat: 30.8342, lng: 35.6014 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Southern Phoenix Busayra', slug: 'phoenix-busayra',
    city: 'الطفيلة', region: 'شرق', location: 'الطفيلة، بصيرا', address: 'بصيرا، الطفيلة',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 15, rating: 3.6, reviewsCount: 14, featured: false,
    phone: ph('5689123'), whatsapp: wa('5689123'),
    amenities: amen(0,4), images: img(10),
    description: 'ملاعب بصيرا الريفية في الطفيلة.',
    coordinates: { lat: 30.7234, lng: 35.7123 }, availableHours: { start: '08:00', end: '20:00' },
  },
  {
    name: 'Tafilah Highland Sports', slug: 'tafilah-highland',
    city: 'الطفيلة', region: 'شمال', location: 'الطفيلة، العيص', address: 'العيص، الطفيلة',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 20, rating: 4.0, reviewsCount: 35, featured: false,
    phone: ph('6790234'), whatsapp: wa('6790234'),
    amenities: amen(0,1,4,5,6), images: img(11),
    description: 'ملعب سداسي في مرتفعات الطفيلة.',
    coordinates: { lat: 30.8712, lng: 35.5934 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Tafilah Valley Arena', slug: 'tafilah-valley',
    city: 'الطفيلة', region: 'غرب', location: 'الطفيلة، وادي اليتم', address: 'وادي اليتم، الطفيلة',
    type: '5v5', turfType: 'عشب طبيعي', surfaceType: 'Natural Grass',
    pricePerHour: 14, rating: 3.5, reviewsCount: 11, featured: false,
    phone: ph('7801345'), whatsapp: wa('7801345'),
    amenities: amen(0,4), images: img(0),
    description: 'ملعب ريفي بعشب طبيعي في وادي الطفيلة.',
    coordinates: { lat: 30.7912, lng: 35.5234 }, availableHours: { start: '08:00', end: '20:00' },
  },

  // ══════════════════════════════════════════════════════════════
  //  MAAN  (3 fields)
  // ══════════════════════════════════════════════════════════════
  {
    name: 'Maan Sports Arena', slug: 'maan-arena',
    city: 'معان', region: 'وسط', location: 'معان، وسط المدينة', address: 'وسط المدينة، معان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 17, rating: 3.8, reviewsCount: 22, featured: false,
    phone: ph('8912456'), whatsapp: wa('8912456'),
    amenities: amen(0,1,4,5), images: img(1),
    description: 'ملاعب معان الرئيسية في وسط البادية الجنوبية.',
    coordinates: { lat: 30.2000, lng: 35.7333 }, availableHours: { start: '08:00', end: '22:00' },
  },
  {
    name: 'Desert Arena Maan', slug: 'desert-arena-maan',
    city: 'معان', region: 'شمال', location: 'معان، الشوبك', address: 'الشوبك، معان',
    type: '5v5', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 15, rating: 3.6, reviewsCount: 14, featured: false,
    phone: ph('9023567'), whatsapp: wa('9023567'),
    amenities: amen(0,4), images: img(2),
    description: 'ملاعب الشوبك السياحية قرب قلعة الشوبك.',
    coordinates: { lat: 30.5123, lng: 35.5567 }, availableHours: { start: '08:00', end: '21:00' },
  },
  {
    name: 'Southern Champions Maan', slug: 'southern-maan',
    city: 'معان', region: 'جنوب', location: 'معان، الأبيض', address: 'الأبيض، معان',
    type: '6v6', turfType: 'عشب صناعي', surfaceType: 'Artificial Grass',
    pricePerHour: 19, rating: 3.9, reviewsCount: 28, featured: false,
    phone: ph('0134678'), whatsapp: wa('0134678'),
    amenities: amen(0,1,4,5,6), images: img(3),
    description: 'أكبر ملعب في معان بمرافق جيدة.',
    coordinates: { lat: 30.1234, lng: 35.7512 }, availableHours: { start: '08:00', end: '22:00' },
  },
];

module.exports = fields;
